version: '3'

services:
  # Discord bot implementation (runs continuously)
  tailscale-monitor:
    build: .
    container_name: tailscale-monitor
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Create a data directory to store all persistent files
      - ./data:/app/data
    environment:
      # Path to store configuration files (optional, defaults to current directory)
      - CONFIG_DIR=/app/data
